# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout release branch from Github
      uses: actions/checkout@v3
      
    - name: Step 2 - Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Step 3 - Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Step 4 - List the current package
      run: ls -a
      
    - name: Step 5 - Run Tests
      run: mvn -B test --file pom.xml
      
    #- name: Step 6 - Run Super-Linter
    #  uses: super-linter/super-linter@v5.0.0
    #  env:
    #    DEFAULT_BRANCH: release
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #- name: Push SpotBugs report
     # uses: jwgmeligmeyling/spotbugs-github-action@v1.2
      # with:
      # A file, directory or wildcard pattern that describes where to find the reports
      # path: 
      # Check run name under which the report is created
      # name: # optional, default is spotbugs
      # Check run title under which the report is created
      # title: # optional, default is SpotBugs Source Code Analyzer report
      # Personal access token (PAT) used to fetch the repository. The PAT is configured with the local git config, which enables your scripts to run authenticated git commands. The post-job step removes the PAT. We recommend using a service account with the least permissions necessary. Also when generating a new PAT, select the least scopes necessary. [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)

      # token: # optional, default is ${{ github.token }}

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Final - Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
